### ISSUE TITLE
Not able to login with the default credentials

### ISSUE THREAD

**Issue by sriram18981** [iluminar/goodwork#1075]
### Your environment:
System:    Host: sriram-vaio Kernel: 5.3.0-53-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
           Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 

Docker Details:
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:
[logs.txt](https://github.com/iluminar/goodwork/files/4908345/logs.txt)

### Installation Method:

Single file installer

### Description:
After successful installation with the Single file installer, not able to login to the application using the default credentials 
email: admin@example.com 
password: secret

logs attached.

### Steps To Reproduce:
Install using the single file installation. try to login.
[logs.txt](https://github.com/iluminar/goodwork/files/4908347/logs.txt)

**Comment by Hasnayeen** [comment]
any error in the browser? what's the http status code?

**Comment by sriram18981** [comment]
> any error in the browser? what's the http status code?

No error shown on the browser. just redirected to the same page. no errors displayed on the console either. below are the logs from console.

nginx_1                | 172.22.0.1 - - [12/Jul/2020:10:32:59 +0000] "POST /login HTTP/1.1" 301 169 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
php_1                  | 172.22.0.6 -  12/Jul/2020:10:32:59 +0000 "GET /index.php" 200
nginx_1                | 172.22.0.1 - - [12/Jul/2020:10:33:06 +0000] "POST /login HTTP/1.1" 301 169 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
php_1                  | 172.22.0.6 -  12/Jul/2020:10:33:06 +0000 "GET /index.php" 200

**Comment by Hasnayeen** [comment]
any error on laravel log file?

**Comment by sriram18981** [comment]
> any error on laravel log file?

no error on the docker-compose logs. if this is a different log file in any of the containers, please let me know the path. I will check.

**Comment by Hasnayeen** [comment]
any error on laravel specific log file in `storage/logs/` directory?

**Comment by sriram18981** [comment]
> any error on laravel specific log file in `storage/logs/` directory?

No. the file is empty.

**Comment by Hasnayeen** [comment]
No idea what's the issue, you can join the community discord server and check if anybody there has any clue https://discord.gg/4DvTQsc

**Comment by sriram18981** [comment]
the issue is not specific to the Linux environment. I have a mac book pro, and its the same scenario there as well.

**Comment by 2bo** [comment]
It seems that the `POST /login` request is redirected by nginx because it is http.

**Comment by 2bo** [comment]
I solved this problem by rewriting .env as follows.(I used port 9999 instead of 80)

```
APP_URL=https://localhost:9999
APP_PROTOCOL=https
APP_PORT=9999
```

**Comment by sriram18981** [comment]
Thanks for the update, @2bo , i tried your changes, its not working for me. 
What approach did you follow for the installation? 
if possible, could you please attach the full ENV file here? 
Did you install for local or for production?
