### ISSUE TITLE
Installing instruction with Docker

### ISSUE THREAD

**Issue by bdjunayed** [iluminar/goodwork#114]
Hi, 
Can we install this repo using Docker also? Also, I had tried to install this repo with the laradock but didn't make it. It would be nice if you kindly show the procedures. Looking forward, thanks.

**Comment by Hasnayeen** [comment]
Pull the latest dev branch and then from root of the project run 
``` bash
docker-compose up -d
```
app will run on `localhost:80` (your port 80 should be free)
if you want to use any other port than change the `APP_PORT=8080`  variable in `.env` file
Let me know if you need any other help

**Comment by bdjunayed** [comment]
Thank you for your kind support. This command worked like charm, after migrate: refresh I've managed to log in to the app successfully. It seems, from the container bash "$ composer install" is woking but the "npm" is not. Looking forward. 
```bash
root@cc3cbf31ba8b:/var/www# npm -v
bash: npm: command not found
```

**Comment by Hasnayeen** [comment]
npm is not installed in the php container, you can install it inside the container, i'll update the docker config soon to make it available by default
