### ISSUE TITLE
Demo Website "goodworkfor.life" currently down

### ISSUE THREAD

**Issue by chrisvasey** [iluminar/goodwork#1148]
### Your environment:
Mac OS V10.15.4 - Chrome V85.0.4183.102 (Official Build) (64-bit)

### Installation Method:

N/A

### Description:
When I try to load the demo website on https://goodworkfor.life it is currently saying connection refused:
<img width="1428" alt="Screenshot 2020-09-20 at 19 59 24" src="https://user-images.githubusercontent.com/7483460/93719707-314f0480-fb7c-11ea-9766-559c6d978dd1.png">
I have checked form an [external monitoring site](https://downforeveryoneorjustme.com/goodworkfor.life?proto=https) and got the same so can confirm it isn't local to me.
If the URL has changed and your doc links need updating let me know and I will happily PR you an update.

Just thought I would let you guys know 🙂
The project looks great by the way!

### Steps To Reproduce:
Visit [https://goodworkfor.life/](https://goodworkfor.life/)

**Comment by chrisvasey** [comment]
After poking around I did find the correct URL linked in the Github info and submitted a PR to update the readme.
If this isn't needed feel free to just close!

**Comment by Rafatlne** [comment]
@chrisvasey Currently this domain has been expired. I contacted with the maintainer of this project. He is right now busy with his startup, that's why he didn't have time to maintain http://goodworkfor.life domain.

**Comment by Hasnayeen** [comment]
the demo is up at `https://demo.goodwork.cloud`
