### ISSUE TITLE
Its just UI, nothing is working

### ISSUE THREAD

**Issue by shahidkarimi** [iluminar/goodwork#1181]
I installed in on Digital ocean droplet. Except the login nothing is working. No button is working. Also there is no error in js console.

What is this?

**Comment by Hasnayeen** [comment]
the app is being restructured right now, frontend isn't wired with backend yet, do not use it in production

**Comment by souravdutt** [comment]
@Hasnayeen, please consider mentioning and highlighting in the readme that the app is currently not usable.
