### ISSUE TITLE
Add new user to "Headquarter" office by default

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#126]

**Comment by krisnaw** [comment]
Any update about this?

How to create a new user? or How to register?

**Comment by Hasnayeen** [comment]
@krisnaw  Registration is through invitation, from admin page you can invite new user via email

**Comment by krisnaw** [comment]
@Hasnayeen 

Thanks for the responses

How to access Admin page if you don't have any users? Any console command to create the first user?

**Comment by Hasnayeen** [comment]
Did you used the single file installer to install the app? there should be a admin user already if you installed via installer, otherwise you've to run seeder

**Comment by krisnaw** [comment]
I installed it manually.

My problem is solved :)

Thanks @Hasnayeen
