### ISSUE TITLE
Use Laravel's asset() helper to assign url of the assets

### ISSUE THREAD

**Issue by dheroefic** [iluminar/goodwork#134]
Hello,

I found this project on the larachat and I would like to implement this for our small team. As I clone this project, set up a bit: `composer install`, `npm install`, copying .env, migrate and seeding, and also `npm run production` (Got an error tho but fixed it by changing this line `node node_modules/cross-env/bin/cross-env.js` to `node node_modules/cross-env/dist/bin/cross-env.js` in package.json).
Tried it and the result is `login.js` file isn't loaded (error as the URL is not correct). That would be wonderful if you could fix that so that we could use this awesome project! Btw I didn't know much about vuejs workflow that maybe I've missed out something.

Thanks.

**Comment by Hasnayeen** [comment]
This project is in early stage of development so yet not stable. v1 will be release in couple of months, so it'll be wise not to use for any serious purpose other than experiments.

Also new commit has been pushed to use asset() helper function to generate all asset url.
Close the issue if solves the issue

**Comment by dheroefic** [comment]
Great at least the JS and CSS is loaded is loaded now 👍
But the images are not loaded tho (URL is still wrong on the dashboard).

**Comment by Hasnayeen** [comment]
what is the `src` attribute of the image, check in elements tab in dev tools

**Comment by dheroefic** [comment]
Okay, This is the only one that doesn't load
![image](https://user-images.githubusercontent.com/25289400/44296153-c4087f80-a2e2-11e8-8176-5c587e89a75d.png)

**Comment by Hasnayeen** [comment]
Latest code should resolve this problem

**Comment by dheroefic** [comment]
Hmm, there's conflict in the dev branch so that I can't test it on the server.
But I'm closing this issue.
