### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by louisyssel** [iluminar/goodwork#159]
I am trying to install Goodwork, and I have followed the instructions to the tee. However, I seem to get to an issue where the installation scripts tries to start Nginx, and the raises the error: 
"ERROR: for goodwork_nginx_1  Cannot create container for service nginx: create .: volume name is too short, names should be at least two alphanumeric characters"

According to some of the research I did on the web, it seems t be a Docker issue. 

Please assist.

**Comment by louisyssel** [comment]
I have now tried all three the installationoptions. Could you possible provide a bit more information on the non docker installation. What are the pre-requisites and what to do after npm install.

**Comment by Hasnayeen** [comment]
@louisyssel If you're setting it for local development then use below command
```bash
./install.sh local
```

for non-docker installation you can install it like a regular laravel application but for real-time chat you need to set up redis server and laravel-echo-server and also need to run a que worker. But I'll suggest to use installer file to set it up using docker

**Comment by louisyssel** [comment]
Thank you, but please see the original message, I am not able to get it to run with Docker because of the nginx issue. Is there specific versions required?

**Comment by Hasnayeen** [comment]
email: admin@example.com
password: secret

for docker related problem can you try this
1. change in the `docker-compose.yaml` or `docker-compose.dev.yaml` (if you're using local)
change line 10 with below
```yaml
      - ./:/var/www
```

**Comment by louisyssel** [comment]
Brilliant, all working now now. Thanks for the help!.

**Comment by Hasnayeen** [comment]
Is that change in docker-composer helped to solve the docker related problem?

**Comment by louisyssel** [comment]
Yes, it seems like it.

**Comment by louisyssel** [comment]
It is currently still install as local, however I did change the docker-compose files, but I am not able to do any actions. I can log in, but I can not edit a user. I can try to onvirte a user, but when clicking the send invite link, nothing happens.

I also want to add SSL cert to  the server. Is this difficult?

**Comment by Hasnayeen** [comment]
the application is under heavy development, so lot of the features are not functional yet. I'll suggest not to use it for production until version 1 release.
You need to provide mail configuration in .`env` file of your choice for invite user or any other email related functionalities.You can use mailgun or similar service.

**Comment by louisyssel** [comment]
I just want to use the basic functionality. I think something is wrong with my installation. You can see it here: It is still with the default credentials. Plese can you just check if the installation is working according to what you believe it dshould be.

Thanks
http://rollo.uc-x.net

**Comment by Hasnayeen** [comment]
i can't login with default credentials so i think  you have successfully updated the credentials
