### ISSUE TITLE
Add ability to comment on discussion

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#173]

**Comment by xkrupa12** [comment]
Can you please explain it further? Especially what you mean by "discussion"? 
I kinda failed to find it - did you mean comments on tasks? Or is it possible to comment on posts? Wasn't able to get into the post detail either...

**Comment by Hasnayeen** [comment]
There is a `discussion` model, so need to add comment option to it. 
Task is to write an api to create a comment to a discussion

![gw-16](https://user-images.githubusercontent.com/9433499/46625983-abd11600-cb57-11e8-80fe-8d392883949c.png)

**Comment by xkrupa12** [comment]
Thanks for clarification, I got confused by that `Create New Post` button

**Comment by Hasnayeen** [comment]
Yeah I'll change the text of that button. Also the discussion details work is on progress, this task is only for the backend part.
