### ISSUE TITLE
Add test for user registration

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#187]

**Comment by bsemexan** [comment]
is this a work in progress? as I can see the routes but that is it

**Comment by Hasnayeen** [comment]
The registration process functionality is already in the code base, this task is for adding a functional test for the registration.

**Comment by bsemexan** [comment]
http://localhost:8000/register -> 404
http://localhost:8000/register/invite -> "SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known (SQL: select exists(select * from `tokens` where `token` = invite) as `exists`)"

**Comment by bsemexan** [comment]
I did the manual set up and it currently is set to db

**Comment by Hasnayeen** [comment]
then set it to the host of your database host name

**Comment by josepostiga** [comment]
@Hasnayeen I think this issue can, now, be closed. Or is anything missing?
