### ISSUE TITLE
Send notification to user when they are added to a project/team/office

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#188]

**Comment by josepostiga** [comment]
@Hasnayeen Is this issue addressed? I can see a PR merged (#196) but this is still open.

Can you confirm the status of this?

**Comment by Hasnayeen** [comment]
mail notification is done but frontend notification not addressed yet, that's why its still open. there is some decision to make regarding frontend notification so currently its on hold kind of

**Comment by josepostiga** [comment]
Ah, oh, got it! Then, maybe, you should add the frontend label? It's probably a nitpick, but it may help track what's missing for the frontend, don't you think?

**Comment by Hasnayeen** [comment]
there is a separate issue for frontend notification [172](https://github.com/iluminar/goodwork/issues/172), here the question more about on backend how to handle notification for frontend,we're already using spatie activitylog package so still haven't decided which one we'll use for frontend notification.
