### ISSUE TITLE
Add api to remove an user from a team/project/office

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#191]
Add an delete request api to remove an user from a team/project/office. request should contain `resource_type` (team/project/office) & corresponding `resource_id` parameter.

**Comment by djaca** [comment]
Hi @Hasnayeen.
I presume that user should be notified, too?
Also, should I test if not member exception is thrown?
I could try this one...

**Comment by Hasnayeen** [comment]
yes, member should be notified, check member add operation, this is similar. and yes test for the exception.
