### ISSUE TITLE
Add status option to tasks

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#194]
Task can have different status e.g in-progress, completed, in-review

**Comment by nbrabant** [comment]
Hello! the task status are fixed to the 3 given or it can have more in the future? Is a color can be used for each status or not?

**Comment by Hasnayeen** [comment]
Status should be separate table and user can add or remove status, should have a color column. task'll be linked to status

**Comment by nbrabant** [comment]
ok, i see no problem for that ;)
When user remove a status, is this status definitively remove, or just removed logically?
And (pehaps for a second time), task have history of status?

**Comment by nbrabant** [comment]
Ok! Just the time for me to create migration, test and have internet and i'll PR the job
