### ISSUE TITLE
Add tag option for task

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#208]

**Comment by MehediDracula** [comment]
Tags are exclusive for tasks or it will be a polymorphic resource?

**Comment by Hasnayeen** [comment]
for now its only task exclusive

**Comment by MehediDracula** [comment]
Alright and one more thing does user requires any kind of special permission to add or delete a tag from a task or a user who has viewing permission for a task can add or delete tags?

**Comment by Hasnayeen** [comment]
anyone who has editing permission on that project/team/office can add or delete tag on a task even if it's not created by that user
