### ISSUE TITLE
Delete a comment

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#210]

**Comment by ananthshenoy** [comment]
Hi @Hasnayeen. I am interested to work on this but can you give me some more details as in which comment has to be deleted and steps to do so.

**Comment by TvtTest** [comment]
Need more clarity over this.

**Comment by Hasnayeen** [comment]
task is to add an api to delete a comment, comment has polymorphic relation with `discussion` and `task`. api will receive `commentable_type` and `commentable_id` as request parameter. Also a check should happen in comment policy for delete request. If you have any more question let me know
