### ISSUE TITLE
Mail notification is not sent

### ISSUE THREAD

**Issue by MehediDracula** [iluminar/goodwork#217]
Whenever a user is added to a project/team/office user should get a mail notification but mail is never sent to the user.

**Comment by MehediDracula** [comment]
Yes, I've found the issue.

In `BecameNewMember` notification an `ErrorException` is thrown because of mismacth `sprintf` arguments.

PR is on the way.

**Comment by Hasnayeen** [comment]
is it about `$groupName` not defined?

**Comment by MehediDracula** [comment]
Not really, the issue was mismatch arguments on `sprintf`

sent a PR #219
