### ISSUE TITLE
Add an api to get all tags

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#245]

**Comment by VigneshMurugan** [comment]
Will pick up this issue and work on it

**Comment by imknight** [comment]
I assume this mean get all tags for a task ?

**Comment by josepostiga** [comment]
@Hasnayeen can you add more details about what you need here?

**Comment by Hasnayeen** [comment]
create an `tags` api to get all tags from db

**Comment by josepostiga** [comment]
@Hasnayeen I think you can close this now, or do you need anything more here?
