### ISSUE TITLE
Update user profiles details

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#246]
updating user details (except avatar) on this page to `users/{user}/profile` route
![gw-4](https://user-images.githubusercontent.com/9433499/46953794-9bb5bb00-d0b0-11e8-906e-14246a1fac42.png)

**Comment by Visovsiouk** [comment]
Can I try my hand on this?

**Comment by Hasnayeen** [comment]
someone already created an pr for this, there is another similar issue [205](https://github.com/iluminar/goodwork/issues/205)
