### ISSUE TITLE
Localization - Add german translation

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#249]

**Comment by voodoods** [comment]
I could take that. 

Before I start: Do I just have to create a german language pack in https://github.com/iluminar/goodwork/tree/master/resources/lang or is there more to consider? Are these language resources referenced somewhere within the project source? Pls provide some information.

**Comment by Hasnayeen** [comment]
https://github.com/iluminar/goodwork/tree/master/resources/lang/en here are all the language resources for english, for german translation of all those files should go inside `de` folder. check https://github.com/iluminar/goodwork/tree/master/resources/lang there are translation for other languages, this will be similar
