### ISSUE TITLE
Long line in message overflow out of box

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#255]
![gw-bug](https://user-images.githubusercontent.com/9433499/47008009-3e2a7880-d15b-11e8-9ceb-6895a6683fbf.png)

**Comment by anandhumanoj** [comment]
I would like to work on this . But can you please guide me how to set up test env please?

**Comment by Hasnayeen** [comment]
check the installation guide https://github.com/iluminar/goodwork/wiki/Installation#setup-using-single-file-installer

**Comment by anandhumanoj** [comment]
okay, thanks

**Comment by anandhumanoj** [comment]
I've submitted a PR as a solution to this issue
