### ISSUE TITLE
Show unread message indicator on icon

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#258]
Show a little indicator for new message when message board is not in focus
![gw-ss](https://user-images.githubusercontent.com/9433499/47018529-c0746600-d176-11e8-8436-bfc9e69ce1c7.png)

**Comment by Visovsiouk** [comment]
I can take this on if still available

**Comment by Hasnayeen** [comment]
yes this is available. we're using [tailwind](https://tailwindcss.com/docs/what-is-tailwind/) framework for css, be sure to use available class rather then adding new one

**Comment by karkowg** [comment]
I've tried working on this but it seems svg doesn't play well with vue's reactivity. Maybe we need to do #244 first.
