### ISSUE TITLE
Localization - add spanish (mexican) translation

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#261]

**Comment by dimitriacosta** [comment]
I think I can help with this, can you tell me what do you need exactly?

**Comment by Hasnayeen** [comment]
check this folder https://github.com/iluminar/goodwork/tree/master/resources/lang , there are translation for several languages, i need spanish (mexican) translation for all the language file in english language folder

**Comment by dimitriacosta** [comment]
Ok, I'm working on it
