### ISSUE TITLE
Revert the message input box to original height (VueJS)

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#277]
When creating message in message box it auto increase according to content, but after creating the message the box remained increased rather then going back to its original heights

expanded after creating message
![gw-ss-3](https://user-images.githubusercontent.com/9433499/47081580-da708000-d22c-11e8-92c0-f957e2aaacad.png)

should be like this
![gw-ss-4](https://user-images.githubusercontent.com/9433499/47081587-de040700-d22c-11e8-9443-768b1ee92f36.png)

**Comment by tthompson899** [comment]
I can work on this.
