### ISSUE TITLE
How to run in Windows for developing without Docker

### ISSUE THREAD

**Issue by waghcwb** [iluminar/goodwork#282]
I want to help on the project, however I'm using Windows without Docker, how can I setup the project environment?

I've already installed composer and xampp. Checked these [steps](https://github.com/iluminar/goodwork/wiki/Installation#setup-usual-way-if-youre-not-using-docker), but didnt figured out how to init the PHP server (I'm not experienced with windows environment but I cannot install Linux for now).

Thanks in advance.

**Comment by Hasnayeen** [comment]
if you have ran all those commands then to run the server in you terminal 
`php artisan serve` 
This command will start a development server at http://localhost:8000:

**Comment by waghcwb** [comment]
Thank you, that worked for me.
`php artisan serve --port=3000`
