### ISSUE TITLE
Problem with Laravel Echo after Setup

### ISSUE THREAD

**Issue by leecop** [iluminar/goodwork#283]
Hello,

I`ve setup the project as described in the contribution guide. After I create a new Team in the Dashboard I get this error when I open the Messages page.

`Error in mounted hook: "ReferenceError: Echo is not defined"`

What is wrong with my setup?

**Comment by Hasnayeen** [comment]
are you using the docker version?

**Comment by leecop** [comment]
No, I'm using the manual setup

**Comment by leecop** [comment]
I runed this commands:
``
php composer install
php php artisan key:generate
npm install
php artisan migrate --seed
``

**Comment by Hasnayeen** [comment]
in manual setup real time chat won't work, you have to setup redis, laravel-echo-server and a que worker to real-time chat to work. But if you're working on #280 then you don't need the real-time feature, you can still work on the task
