### ISSUE TITLE
Localization - add korean translation

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#284]

**Comment by Hasnayeen** [comment]
the language files are in `resources/lang` folder, for each language there is separate folder. all the files in `en` folder contains the text that needs to be translated. so create a `ko_KR` folder and copy all the files from `en` and translate the text in array values

**Comment by r3dr4bb1t** [comment]
I'm on it

**Comment by r3dr4bb1t** [comment]
I've tried pr but it fails on travis ci
all I did is added ko_KR folder as u mentioned with translation.
I can't understand the error log.
please help me~

<img width="823" alt="2018-11-01 1 50 33" src="https://user-images.githubusercontent.com/31888502/47833230-13882300-dddd-11e8-8766-0376c3c77f84.png">
<img width="855" alt="2018-11-01 1 50 43" src="https://user-images.githubusercontent.com/31888502/47833231-13882300-dddd-11e8-9267-41f5ee393647.png">
<img width="762" alt="2018-11-01 1 50 51" src="https://user-images.githubusercontent.com/31888502/47833233-1420b980-dddd-11e8-95c7-207687918b84.png">

**Comment by Hasnayeen** [comment]
@r3dr4bb1t issue solved, thanks for the translation :+1:
