### ISSUE TITLE
Teams list does not update after creating a team

### ISSUE THREAD

**Issue by waghcwb** [iluminar/goodwork#295]
When creating a new team

![image](https://user-images.githubusercontent.com/6169950/47155471-308c0480-d2bb-11e8-99e5-0a5e534daf67.png)

There's a message of successfully created a team, but the team list is not updated until a refresh is made on the page.

**Comment by tthompson899** [comment]
I can work on this if it hasn't been completed already.

**Comment by Hasnayeen** [comment]
No pr has been opened for this yet

**Comment by chojisan** [comment]
I think guest user is not authorized to add on team

**Comment by tthompson899** [comment]
Is this functionality supposed to be for a guest or an admin?
Also, are there any admin credentials? I haven't seen them if there are.

**Comment by waghcwb** [comment]
@chojisan, no because if we refresh de the page the team appears on the list.

@tthompson899, I've simulated this issue on local environment with this credentials: admin@example.com, secret

**Comment by chojisan** [comment]
the variable on partials/teams.vue must be changed..it uses project instead of team
