### ISSUE TITLE
Localization - add Turkish translation

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#299]

**Comment by ermanyilmaz** [comment]
I can help you about translation If you still need it

**Comment by Hasnayeen** [comment]
@ermanyilmaz go ahead

**Comment by ermanyilmaz** [comment]
Hi mate. If you reopen the issue . I will send the Turkish translation of the validation.php.

**Comment by ermanyilmaz** [comment]
Hi mate there may be problem about user_can_mention_other_user_when_creating_comment . I am getting error when travis build works.

**Comment by Hasnayeen** [comment]
@ermanyilmaz thanks for the translation, I appreciate it :+1:
