### ISSUE TITLE
Password Reset Form page messed view

### ISSUE THREAD

**Issue by juliardi** [iluminar/goodwork#313]
I am trying the demo on this repository, and then when opening the password reset page, it doesn't render correctly like the css class doesn't apply to that page
Here is a screenshot :
![screenshot_20181020_092637](https://user-images.githubusercontent.com/4223302/47250417-d1f59080-d44a-11e8-891e-2c687d92a7be.png)
if this indeed is not the correct behavior and not my browser's problem, I want to open a pull request to address this issue

**Comment by Hasnayeen** [comment]
@juliardi this page has not been updated after we moved from `bulma` to `tailwindcss` and not a browser issue, you're welcome to open pr to fix this, but remember to use tailwindcss default classes. check login and register vue components, this is similar.
