### ISSUE TITLE
Move focus on input when modal is opened (VueJS)

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#317]
Right now all the form modal doesn't auto focus on input element

**Comment by MatthijsBlankevoort** [comment]
Hi, I'd like to pick this one up!

**Comment by Hasnayeen** [comment]
@MatthijsBlankevoort go ahead

**Comment by MatthijsBlankevoort** [comment]
So to make it clear: you want to have the first input element of all modals (when creating tasks for example) autofocussed so users can start typing right away without clicking the input first?

**Comment by Hasnayeen** [comment]
yes, that's correct
