### ISSUE TITLE
Add a create form to create an event (VueJS)

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#321]
Add a create button in events section and when clicked should open a modal form to create event, similar to `createTaskForm.vue` component

**Comment by Hasnayeen** [comment]
what do you mean by `/request` ?

**Comment by CapitanFindusFI** [comment]
whoops, saw on other issues a `/request` thing to say like "can I work on it?" (had a bot response). Anyway, can I work on it?

**Comment by Hasnayeen** [comment]
yes
