### ISSUE TITLE
Add an api to check if username exists

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#334]
Add an api to check provided username in request already exists in database or not

**Comment by V1shvesh** [comment]
@Hasnayeen Can I work upon this issue?

**Comment by ianmustafa** [comment]
@V1shvesh you beat me to it :joy:

**Comment by Hasnayeen** [comment]
yes you can

**Comment by Hasnayeen** [comment]
@ianmustafa there are other issue you can work on https://github.com/iluminar/goodwork/labels/hacktoberfest

**Comment by ianmustafa** [comment]
@Hasnayeen I'm working on Bahasa Indonesia language support, should be done in minutes

**Comment by James-N-M** [comment]
if nobody ended up completing this I'll pick it up
