### ISSUE TITLE
Dropdown menu does not show in discussion details (Vuejs)

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#335]
when clicked on ellipsis menu button it doesn't show the menu
![gw-ss-6](https://user-images.githubusercontent.com/9433499/47265405-54fd1080-d549-11e8-92c4-a7fb171674ea.png)

should be like this
![gw-ss-7](https://user-images.githubusercontent.com/9433499/47265411-6d6d2b00-d549-11e8-82cb-3c58212502ab.png)

**Comment by CometS1** [comment]
I'll take a look into this issue. Do you know where the ellipsis menu is located in the code?

**Comment by Hasnayeen** [comment]
in this file `resources/assets/js/components/partials/discussionDetails.vue`

**Comment by Hasnayeen** [comment]
you need to install composer on your systems first if you're manually installing the project. but if you can use docker then it'd be best, then you can install just running a single file

**Comment by CometS1** [comment]
There is no sudo command for windows. Is the install Linux specific?

**Comment by Hasnayeen** [comment]
remove the sudo in `install.sh` file and then run the file

**Comment by Hasnayeen** [comment]
add this `COMPOSE_CONVERT_WINDOWS_PATHS=1` in `.env` file and try again, check if that works
