### ISSUE TITLE
Send notification to user when they are mentioned

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#338]
Send mail and database to user when they are mentioned in task,comments or messages

**Comment by djaca** [comment]
Hi,

can you give more details?

**Comment by Hasnayeen** [comment]
when a user is mentioned in comment, message or task description a reference is created in mention table.  when that happen the user who is mentioned should get database and mail notification

**Comment by djaca** [comment]
Ok... There is an issue with mentioned users array: If same user is mentioned twice, there will be two inserts in MentionRepository@create with the same username, therefore two notifications. Maybe, in .vue files to filter mention users to not repeat same username or, maybe even better, to do regex for '@username' from body of comment/message or task description?

**Comment by Hasnayeen** [comment]
will make separate issue for that, meanwhile you can do the notification part
