### ISSUE TITLE
Localization - add simplified Chinese translation

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#383]

**Comment by YuechengWu** [comment]
Hi @Hasnayeen , where should the Chinese translation added?

**Comment by Hasnayeen** [comment]
Under `resources/lang` folder a folder should be created with locale code and will contain translation files. English translation files are under `resources/lang/en` folder.

**Comment by YuechengWu** [comment]
@Hasnayeen, thank you, I can help with this, is it ok if I name the folder ch-sim to indicate it's Chinese Simplified?

**Comment by Hasnayeen** [comment]
no folder name should be according to language locale code, I believe for simplified chinese its `zh-CN`

**Comment by YuechengWu** [comment]
Ok, got it. Thanks.
