### ISSUE TITLE
Add an api to update status of a task

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#386]
route should be: `task\{task}\statuses`
and controller: `TaskStatusController`

**Comment by Ashrey** [comment]
taken

**Comment by Hasnayeen** [comment]
you can use `git checkout -f public` if you don't want to commit compiled files from laravel mix, this will revert all files under public to its original state

**Comment by Hasnayeen** [comment]
No, one task will have only one status, for example it may have a status `started` , then it can change its status to `in review` and then again change into `done`.route should be `tasks/{task}/statuses` and controller should be `TaskStatusController`

**Comment by djaca** [comment]
[Read here](https://stackoverflow.com/questions/37782618/what-is-the-different-between-with-and-load-in-laravel)
