### ISSUE TITLE
Add option to backup & restore db data

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#416]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/iluminar/goodwork/issues/416)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($20.00)
### Submitted pull Requests
- [#468 backup and restore database with dropbox](https://issuehunt.io/r/iluminar/goodwork/pull/468)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/iluminar/goodwork/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Hasnayeen** [comment]
An option on admin section should be added to backup db data and option to send to somewhere like google drive or any cloud storage, and restoring db from that backup file

**Comment by rapulu** [comment]
Okay...I will handle it.

**Comment by deltasquare4** [comment]
https://github.com/iluminar/goodwork/pull/468
