### ISSUE TITLE
Write backend functionality for upload files in files page

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#42]
Save files to file system and database when a user upload a files

**Comment by xkrupa12** [comment]
I took a look into that and it looks like you've got it covered. All I needed to make it work was to run `php artisan storage:link` to create symlink between storage and public folder, so you can access uploaded avatars.

**Comment by Hasnayeen** [comment]
No, upload avatars is different task and is implemented. This is for uploading file in files section, user can upload files in project/teams/office file section. they can vie those files in files section. They can also use those files in task description, in discussion or other area. Its little complicated right now. spatie medialibrary will be used to handle file related stuff
![aaaaa](https://user-images.githubusercontent.com/9433499/46723682-31f57580-cc9a-11e8-9343-d3a0fe8b7193.png)

**Comment by xkrupa12** [comment]
Oh I see, thanks for explanation. I might take a look at that

**Comment by Hasnayeen** [comment]
If you're interested I can invite you to the app (https://goodworkfor.life), we can have more discussion there easily. If you're interested send me your email address to me searching.nehal@gmail.com

**Comment by Hasnayeen** [comment]
Cool,well you don't have to code all the time, we can discuss about code quality, best practice, feature discussion and other stuff. Also I'm trying to make the application developer focused so will love to have feedback from developers, so you'll get some ideas when you use it.

I'll try to create some backend related issues soon
