### ISSUE TITLE
Fatal error when install via docker for local

### ISSUE THREAD

**Issue by richardtks** [iluminar/goodwork#444]
Hi,

I am trying to install the goodwork for local through docker following the instruction [here](https://github.com/iluminar/goodwork/wiki/Installation#setup-using-docker).

However, I am getting this error and some problems as shown as below:
![image](https://user-images.githubusercontent.com/43637878/49850834-0158c600-fe1a-11e8-8ae1-1d3bad8f3b6f.png)

Besides, I am also getting these error when running `./cmd composer update`
![image](https://user-images.githubusercontent.com/43637878/49850899-47ae2500-fe1a-11e8-87fb-11490666c1f1.png)

Please kindly advise me how to resolve this issue. Thank you. :smile:

**Comment by Hasnayeen** [comment]
did you used the installer to install the app?

**Comment by richardtks** [comment]
Yes, I entered the command install.sh /local

**Comment by richardtks** [comment]
@Hasnayeen, any update?

**Comment by richardtks** [comment]
@Hasnayeen, I managed to solve the error as mentioned last time, but after that I hit another error. It seems that we can't cache the route with the closure? Do you have the same problem?

![image](https://user-images.githubusercontent.com/43637878/50271871-10222700-0471-11e9-9020-c2f94509a00f.png)

**Comment by Hasnayeen** [comment]
@richardtks no, I don't see that problem. But the app should run still, Is the app running properly?

How did you manage to solve the last problem?

**Comment by Hasnayeen** [comment]
I'll remove closure routes later so that routes can be cached

**Comment by richardtks** [comment]
@Hasnayeen, bcmath was not installed in the php:7.2-fpm container. 

I added bcmath in the docker file:
`RUN apt-get update && apt-get -y install libpng-dev zip unzip git && docker-php-ext-install pdo_mysql gd bcmath`

**Comment by Hasnayeen** [comment]
fixed by https://github.com/iluminar/goodwork/commit/7c3942c5289e7337150ccd94514afb43abfe4c9a

**Comment by richardtks** [comment]
@Hasnayeen, thank you, now I able to run the install successfully without any problem! thanks :smile:
