### ISSUE TITLE
Demo Instance Limitations

### ISSUE THREAD

**Issue by jakimfett** [iluminar/goodwork#457]
Currently, the [demo of goodwork](https://github.com/iluminar/goodwork#demo) throws a 403 Access Denied error when navigating to one of the projects visible on the logged-in site.

![access_denied 2019 01 27_12 54 49](https://user-images.githubusercontent.com/2565176/51806804-55d1cc80-2233-11e9-9d8b-5807363a28c8.png)

Additionally, attempting to create a new project fails:
![action_denied 2019 01 27_12 53 32](https://user-images.githubusercontent.com/2565176/51806816-7437c800-2233-11e9-82e2-f51ad45f936d.png)

Are these intentional limitations?

**Comment by Hasnayeen** [comment]
@jakimfett yes this limitations are intentional, the guest has limited permissions

**Comment by jakimfett** [comment]
Just to clarify:
It's intentional to prevent the demo user from seeing anything, or doing anything, once they have logged in?

**Comment by Hasnayeen** [comment]
No, they have access to some projects, teams and offices where they can create tasks, discussions etc.

**Comment by jakimfett** [comment]
Specifically which projects, teams, or offices might I examine to examine the functionality mentioned?  
When I attempted to access the visible projects on the home page of the demo, each of them returned the same error, would it not make more sense to hide project(s) if a user has not the permissions to (at least) view the project in question?

**Comment by Hasnayeen** [comment]
Project/team named "For Guests" should be accessible by guest user, are you facing any problem on accessing those?

Right now every project is visible but later there will be option for admin turn on/off visibility of private projects.

**Comment by jakimfett** [comment]
Was able to access the project.  
![goodwork_2019 02 15_14 07 47](https://user-images.githubusercontent.com/2565176/52887124-7ce13700-312b-11e9-8f0a-ec39641da3f8.png)

Could not add a new task:  
![goodwork_2019 02 15_14 09 36](https://user-images.githubusercontent.com/2565176/52887172-a306d700-312b-11e9-9ddc-055af0dff2be.png)


Is a project the same thing as a team?  
Would it not make more sense to hide private projects by default?

**Comment by Hasnayeen** [comment]
project, team and office is basically same thing with same tools with same functionality.

> Would it not make more sense to hide private projects by default?

it would, this will be implemented in future.
