### ISSUE TITLE
 php_network_getaddresses: getaddrinfo failed

### ISSUE THREAD

**Issue by ahmadlatif1084** [iluminar/goodwork#459]
While Installing on local,when everything is done,it gives me an error while running command of 
> php artisan migrate

My system configuration
->PHP 7.2.5
->Windows 10 and 64 bit.

![screenshot_4](https://user-images.githubusercontent.com/24588818/51885441-4aa2ac00-23ad-11e9-817d-ee0bcc115c1b.png)

**Comment by cf-git** [comment]
Hello. Your php extension sqlite is absent.
You need config your php.ini and uncomment extension php_sqlite.dll

**Comment by ahmadlatif1084** [comment]
Thanks,I have done it already and that's why i closed the issue 👍
