### ISSUE TITLE
Socket.io not found and Echo Error.

### ISSUE THREAD

**Issue by ahmadlatif1084** [iluminar/goodwork#460]
Please find any solutions and help me on this.Thanks.

![errorgoodwork](https://user-images.githubusercontent.com/24588818/51962054-a1c58100-2480-11e9-8be2-a6abd044558b.png)

**Comment by Hasnayeen** [comment]
assuming you installed the project manually, 3 more steps have been added on (installation guide)[https://github.com/iluminar/goodwork/wiki/Installation#setup-usual-way-if-youre-not-using-docker]. Please try the last 3 steps.

**Comment by ahmadlatif1084** [comment]
I Installed redis and laravel echo server globally.I am stuck with the configuration with the project.About port and other things.It is not working as required.Please see the below code.

While i run redis-cli :

**C:\WINDOWS\system32>redis-cli
127.0.0.1:6379>**

While i run laravel echo server with following configuration.
![laravel_echo_servor](https://user-images.githubusercontent.com/24588818/52103368-204c2b00-2607-11e9-9915-1cdd52de1548.png)

**Comment by Hasnayeen** [comment]
you've to symlink storage folder, `$ php artisan storage:link`

also use development mode for `laravel-echo-server` and proper `authHost` value in the file.

**Comment by ahmadlatif1084** [comment]
Cannot read property 'id' of undefined in vendor.min.js .

Why is that so ?

**Comment by Hasnayeen** [comment]
issue has been fixed in latest commit,please check if that solves the problem, if not reopen the issue

**Comment by ahmadlatif1084** [comment]
This issue is already closed by you.How can i reopen it ? My system still gives me an error mentioned below.
**Cannot read property 'id' of undefined in vendor.min.js .**

**Comment by Hasnayeen** [comment]
please pull latest code and clear browser cache and retry.

**Comment by ahmadlatif1084** [comment]
Okay let me try that again.

**Comment by Hasnayeen** [comment]
I don't have experience with windows 10. are you facing any specific error?

**Comment by ahmadlatif1084** [comment]
Certainly given below on windows 10:

**Cannot read property 'id' of undefined in vendor.min.js .**
**Cannot read property 'state' of undefined**

**Comment by ahmadlatif1084** [comment]
May be,It would be due to configurations of redis or echo server ? isn't ?

**Comment by ahmadlatif1084** [comment]
On which system it will work flawless ? Is it Linux ?

**Comment by djaca** [comment]
@ahmadlatif1084 Maybe you can try Homestead...

**Comment by Hasnayeen** [comment]
i've pushed new commit, should fix **Cannot read property 'state' of undefined** error, can you check that

**Comment by ahmadlatif1084** [comment]
> @ahmadlatif1084 Maybe you can try Homestead...

What do you sense by homestead and how it is going to effect my code into fully running flawless ?

**Comment by ahmadlatif1084** [comment]
> i've pushed new commit, should fix **Cannot read property 'state' of undefined** error, can you check that

@Hasnayeen 

Assured,let me pull new commits and check later.I will get back to you,If required.

**Comment by ahmadlatif1084** [comment]
Fantastic,I have pulled the code and tried it again and everything starts working.Messages is not running smoothly and didn't get the main idea of using redus along with it.Can you please help me onto this ? .By the way,very thankful for your guidance's,directions and supervisions. 👍 
@Hasnayeen @djaca

**Comment by djaca** [comment]
Well, demo is working...
If you want to use Win10, best option is to use Laravel Homestead. Then, follow instructions [here](https://github.com/iluminar/goodwork/wiki/Installation#setup-usual-way-if-youre-not-using-docker).
