### ISSUE TITLE
Column not found: 1054 Unknown column 'start_date' 

### ISSUE THREAD

**Issue by rapulu** [iluminar/goodwork#461]
![goodwork_error](https://user-images.githubusercontent.com/8965252/52066786-8ab68a00-2579-11e9-8fb3-22b1eead51e9.png)
I get this database related error when i try to start the application after pulling the recent changes.

**Comment by Hasnayeen** [comment]
@rapulu you need to run new migration files

**Comment by rapulu** [comment]
@Hasnayeen I Did it came up with that error on terminal too.

**Comment by ahmadlatif1084** [comment]
@rapulu did you tried ?
 
**php artisan migrate:refresh
php artisan db:seed**

**Comment by rapulu** [comment]
![error_good woodwork](https://user-images.githubusercontent.com/8965252/52135129-66c07a80-2645-11e9-8dcb-cbc822e784e6.png)
This happens during migration...As you can see is coming from my terminal @ahmadlatif1084 @Hasnayeen

**Comment by rapulu** [comment]
![migration_file](https://user-images.githubusercontent.com/8965252/52145260-cb3d0300-2660-11e9-8f83-1384c3a42e89.png)

So i just found the solution to this problem. this migration file line of code `$table->date('start_date')->default(' ')->comment('date of start of the cycle');`.
Why is start_date defaulted to empty? It breaks mysql syntax rule. I changed it to nullable `$table->date('start_date')->nullable()->comment('date of start of the cycle');` and it works perfectly can i push this changes? @Hasnayeen

**Comment by Hasnayeen** [comment]
issue has been fixed in latest commit
