### ISSUE TITLE
manual install

### ISSUE THREAD

**Issue by sleepm** [iluminar/goodwork#466]
in [wiki](https://github.com/iluminar/goodwork/wiki/Installation#setup-usual-way-if-youre-not-using-docker)
you forget ./artisan migrate ./artisan db:seed
and laravel-ecoh-server init
thanks your goodwork

**Comment by Hasnayeen** [comment]
thanks, wiki updated and `laravel-echo-server init` is not needed, laravel-echo-server config file already exist
