### ISSUE TITLE
Fatal error when install via docker

### ISSUE THREAD

**Issue by kimchanger** [iluminar/goodwork#476]
I got this mistake when I installing followed the manual.

```
ERROR: for nginx  Cannot create container for service nginx: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for laravel_echo_server  Cannot create container for service laravel_echo_server: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
```

docker version:
`
Docker version 18.09.6, build 481bc77
`

docker-compose version:
`
docker-compose version 1.24.0, build 0aa5906
`
OS: `ubuntu`

**Comment by kimchanger** [comment]
branch:  `master`

**Comment by Hasnayeen** [comment]
you need a `SSL_CERT_DIR` variable in `.env` file with a value (directory path where you have stored your ssl certificate for the domain).
If you're using in local development then use `./install.sh local` command or `docker-compose.dev.yml` file. Let me know if it solves the problem

**Comment by kimchanger** [comment]
@Hasnayeen   Yes.    I forgot to configure this.  There is no error now.  Thanks.
