### ISSUE TITLE
403 — Access denied in the Demo project with demo credentials

### ISSUE THREAD

**Issue by Maxiride** [iluminar/goodwork#482]
Hello, I was browsing for project management solutions and stumbled upon this repo, however, when loading the demo page with the guest credentials the only available project "For Guests" returns a 403 error upon loading.

1. Open the demo site
1. Login with demo credentials
1. Try to open the "For Guests" project

Edit:
This is **not** related to https://github.com/iluminar/goodwork/issues/457#issuecomment-463053359 as I'm not referring to other interactions with other project boards. The guest one itself can't be opened.

**Comment by Hasnayeen** [comment]
it's fixed now, thanks.
