### ISSUE TITLE
Task filter

### ISSUE THREAD

**Issue by Oreolek** [iluminar/goodwork#500]
I'd want a comprehensive filter for the tasks, so I could quickly manage more than 50 of them

**Comment by Hasnayeen** [comment]
@Oreolek can you explained a bit more? do you mean, to select multiple task with a filter and apply a action to them?

**Comment by Oreolek** [comment]
Just the view filter, to find the tasks quicker by status.

**Comment by Hasnayeen** [comment]
resolved by https://github.com/iluminar/goodwork/commit/45aba47275e59e3bbf02ff11c52933fa910cb43a
