### ISSUE TITLE
localhost installation

### ISSUE THREAD

**Issue by m2ura** [iluminar/goodwork#508]
Hello,

 I Am trying to install it on my local machine on apache server, see below

<Directory /var/www/laravel/goodwork/public/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
    </Directory>

But I get the below error

![goodwork](https://user-images.githubusercontent.com/13012135/60125772-cce0a200-978c-11e9-983b-76e9aaca6fd0.png)

**Comment by Hasnayeen** [comment]
I see the uri is `project.conf`, there is no route like that in the app, might wanna check out what url you actually trying to reach.

**Comment by m2ura** [comment]
I managed to fix it but now, as an Admin, I can't create a project  nor create a team, It gives me the below error...

![good](https://user-images.githubusercontent.com/13012135/60139447-48068000-97ae-11e9-8ccc-0fbda96efd62.png)

**Comment by Hasnayeen** [comment]
@m2ura did you run the seeder, if not please run `php  artisan db:seed`

**Comment by m2ura** [comment]
I ran php artisan migrate --seed, but still the same issue.

**Comment by Hasnayeen** [comment]
can you check the `permission_settings` table is there any records in the table

**Comment by m2ura** [comment]
@Hasnayeen I took a sceen shot of it

![permision settings](https://user-images.githubusercontent.com/13012135/60199388-1e983380-9844-11e9-813f-968af3c2f97b.png)

**Comment by Hasnayeen** [comment]
can you also post the `role_has_permission` table screenshot?

**Comment by m2ura** [comment]
![role has permission](https://user-images.githubusercontent.com/13012135/60199899-37551900-9845-11e9-8594-137fd6b4b923.png)

**Comment by Hasnayeen** [comment]
no problem there, can you check the laravel log file for any error.

**Comment by m2ura** [comment]
This is what I had on logs, then I remigrated and seeded

[2019-06-26 15:54:14] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'users_username_unique' (SQL: insert into `users` (`name`, `username`, `email`, `active`, `password`, `created_at`, `updated_at`) values (Admin, admin, admin@example.com, 1, $2y$10$5bm5fiR5xYM02FVT7MU4z.GHRS5Q4eIlBXhcL2H98mnZDSHD7pcu6, 2019-06-26 15:54:13, 2019-06-26 15:54:13)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'users_username_unique' (SQL: insert into `users` (`name`, `username`, `email`, `active`, `password`, `created_at`, `updated_at`) values (Admin, admin, admin@example.com, 1, $2y$10$5bm5fiR5xYM02FVT7MU4z.GHRS5Q4eIlBXhcL2H98mnZDSHD7pcu6, 2019-06-26 15:54:13, 2019-06-26 15:54:13)) at /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'users_username_unique' at /var/www/laravel/goodwork/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'users_username_unique' at /var/www/laravel/goodwork/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
[stacktrace]
#0 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#1 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `us...', Array, Object(Closure))
#2 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `us...', Array)
#3 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert('insert into `us...', Array)
#4 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2628): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into `us...', Array, 'id')
#5 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1338): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(823): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(788): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(651): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(793): Illuminate\\Database\\Eloquent\\Model->save()
#10 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1027): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}(Object(App\\Core\\Models\\User))
#11 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(794): tap(Object(App\\Core\\Models\\User), Object(Closure))
#12 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create(Array)
#13 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1608): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'create', Array)
#14 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1620): Illuminate\\Database\\Eloquent\\Model->__call('create', Array)
#15 /var/www/laravel/goodwork/database/seeds/AdminUserSeeder.php(23): Illuminate\\Database\\Eloquent\\Model::__callStatic('create', Array)
#16 [internal function]: AdminUserSeeder->run()
#17 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#18 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(122): Illuminate\\Container\\Container->call(Array)
#22 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(42): Illuminate\\Database\\Seeder->__invoke()
#23 /var/www/laravel/goodwork/database/seeds/DatabaseSeeder.php(16): Illuminate\\Database\\Seeder->call('AdminUserSeeder')
#24 [internal function]: DatabaseSeeder->run()
#25 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#26 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#28 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#29 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(122): Illuminate\\Container\\Container->call(Array)
#30 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): Illuminate\\Database\\Seeder->__invoke()
#31 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php(122): Illuminate\\Database\\Console\\Seeds\\SeedCommand->Illuminate\\Database\\Console\\Seeds\\{closure}()
#32 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\\Database\\Eloquent\\Model::unguarded(Object(Closure))
#33 [internal function]: Illuminate\\Database\\Console\\Seeds\\SeedCommand->handle()
#34 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#35 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#36 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#37 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#38 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#39 /var/www/laravel/goodwork/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#40 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#41 /var/www/laravel/goodwork/vendor/symfony/console/Application.php(901): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 /var/www/laravel/goodwork/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Seeds\\SeedCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 /var/www/laravel/goodwork/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /var/www/laravel/goodwork/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /var/www/laravel/goodwork/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 {main}
"}

**Comment by Hasnayeen** [comment]
can you visit the `admin` page?

**Comment by m2ura** [comment]
This is when I Add new project as Admin 
![403](https://user-images.githubusercontent.com/13012135/60200909-63719980-9847-11e9-94a1-b33aecfb8cf4.png)

And Headers
![post headers](https://user-images.githubusercontent.com/13012135/60200985-96b42880-9847-11e9-9453-1c37b50a3cf7.png)

**Comment by Hasnayeen** [comment]
can you visit the `/admin` page? click the profile avatar and in dropdown menu you'll see admin link? can you visit that?

**Comment by m2ura** [comment]
I clicked then I got this

![Admin](https://user-images.githubusercontent.com/13012135/60201293-370a4d00-9848-11e9-9a37-fe30e79540f9.png)

**Comment by Hasnayeen** [comment]
what's the `role_id` of admin user in `users` table and post the `roles` table screeenshot

**Comment by m2ura** [comment]
Okay, it seems like users table is missing, there is team_user, office_user, and project_user table.

**Comment by Hasnayeen** [comment]
how can you login without a `users` table, you wouldn't be able to login if there is no `users` table. check again

**Comment by m2ura** [comment]
These are the only tables that wer migrated, not sure how I login without users table.
![shot1](https://user-images.githubusercontent.com/13012135/60202136-3e325a80-984a-11e9-8a3a-75be91fb4ace.png)

![shot2](https://user-images.githubusercontent.com/13012135/60202154-45596880-984a-11e9-8e4f-5f456d111a9f.png)

**Comment by Hasnayeen** [comment]
run `php artisan migrate:fresh --seed`

**Comment by m2ura** [comment]
Done... Role id...

![role](https://user-images.githubusercontent.com/13012135/60204358-f82bc580-984e-11e9-929a-eee898929709.png)

**Comment by Hasnayeen** [comment]
`role_id` should be 1

**Comment by m2ura** [comment]
Thank you very much my guy, you have helped me :dancing_men: 

![adminn](https://user-images.githubusercontent.com/13012135/60204689-b64f4f00-984f-11e9-9713-a7c1480473fc.png)

**Comment by Hasnayeen** [comment]
which version are you using? that looks outdated. make sure to pull latest commits from `master` branch

**Comment by Hasnayeen** [comment]
current admin page looks like this 
![FireShot Capture 005 - GOODWORK - Admin Panel - goodwork local](https://user-images.githubusercontent.com/9433499/60204935-ced06100-9871-11e9-9134-99b95a44e46e.png)
