### ISSUE TITLE
HELP WANTED

### ISSUE THREAD

**Issue by Kaperskyguru** [iluminar/goodwork#510]
Please i want to contribute to this project. can i get a guide as i'm barely new, but really want to be a contributor. Thanks. Any help will be appreciated.

**Comment by Hasnayeen** [comment]
Hello, first of all thanks for considering to contribute to the project.
Check this guide on [how to install](https://github.com/iluminar/goodwork/wiki/Installation) and this guide on [How to Contribute](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline)

If you have any other question please let me know
