### ISSUE TITLE
how to localize the app ?

### ISSUE THREAD

**Issue by fahedaljghine** [iluminar/goodwork#514]
Thank you all for this great app.

I tried ti play this around I've  changed the local and fallback_local in config/app.php but no change
I found config/locale and ar is supported but I didn't know how to change the lang of the app.

**Comment by Hasnayeen** [comment]
@fahedaljghine you have to change it from your profile in the app frontend not backend. Go to your profile page and you'll see preferred language option.

**Comment by fahedaljghine** [comment]
Thank you so much again 😍😍😍
