### ISSUE TITLE
Creating goodwork_laravel_echo_server_1 ... error

### ISSUE THREAD

**Issue by xamix-as** [iluminar/goodwork#563]
Hi,
Could you please check this error?
`root@ubuntu-s-1vcpu-1gb-tor1-01:~/goodwork# ./cmd up -d
goodwork_redis_1 is up-to-date
goodwork_db_1 is up-to-date
Creating goodwork_laravel_echo_server_1 ... 
goodwork_php_1 is up-to-date
Creating goodwork_nginx_1 ... 
Creating goodwork_laravel_echo_server_1
goodwork_worker_1 is up-to-date
Creating goodwork_laravel_echo_server_1 ... error

ERROR: for goodwork_laravel_echo_server_1  Cannot create container for service laravel_echo_server: create .: volume name is too short, names should be at leastCreating goodwork_nginx_1 ... error

ERROR: for goodwork_nginx_1  Cannot create container for service nginx: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for nginx  Cannot create container for service nginx: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for laravel_echo_server  Cannot create container for service laravel_echo_server: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.`

**Comment by Hasnayeen** [comment]
you need a `SSL_CERT_DIR` variable in `.env` file with a value (directory path where you have stored your ssl certificate for the domain).
If you're using in local development then use `./install.sh local` command or docker-compose.dev.yml file.
