### ISSUE TITLE
Tasks are not persistent

### ISSUE THREAD

**Issue by AienTech** [iluminar/goodwork#594]
Hey there,

I followed the docker installation instructions. there were some minor bugs which I've fixed them. But surprisingly when creating a task for a project, it shows that the task is created (indeed it's available in database) and after a refresh, it's gone!

I tested it in both local and production envs.

**Comment by Hasnayeen** [comment]
By "refresh", do you mean database refresh? Is it available in database but not showing in the frontend or its gone from database? Please provide more info, thanks.

**Comment by AienTech** [comment]
Hi there,

Im sorry for the lack of enough info. Yes it was on the front end. I checked the database and the tasks are actually there, after I save them. But with a refresh on the web page (tasks page) they won‘t appear on the page.

Aien Saidi

________________________________
Von: Nehal Hasnayeen <notifications@github.com>
Gesendet: Montag, September 2, 2019 8:35 AM
An: iluminar/goodwork
Cc: Aien Saidi; Author
Betreff: Re: [iluminar/goodwork] Tasks are not persistent (#594)


By "refresh", do you mean database refresh? Is it available in database but not showing in the frontend or its gone from database? Please provide more info, thanks.

**Comment by Hasnayeen** [comment]
So the task is there, by default it shows tasks of current cycle, if you click on the cycles menu right under project name you'll see the selected cycle, you can deselect it or select another cycle. Also there is filter menu and by default task with "ToDo" status are shown, if you deselect it, all task will be shown.
Let me know if this solves your problem.

**Comment by AienTech** [comment]
Hi,

Thanks for the info. I didn’t knew that the cycle field was required. Maybe that could be a UI feature?

Aien Saidi

________________________________
Von: Nehal Hasnayeen <notifications@github.com>
Gesendet: Montag, September 2, 2019 1:30 PM
An: iluminar/goodwork
Cc: Aien Saidi; Author
Betreff: Re: [iluminar/goodwork] Tasks are not persistent (#594)


So the task is there, by default it shows tasks of current cycle, if you click on the cycles menu right under project name you'll see the selected cycle, you can deselect it or select another cycle. Also there is filter menu and by default task with "ToDo" status are shown, if you deselect it, all task will be shown.
Let me know if this solves your problem.

**Comment by Hasnayeen** [comment]
Cycle is not required. If you didn't selected a cycle, you can still see the task on the task board. just deselect the currently selected cycle and all task without a cycle will be shown

**Comment by AienTech** [comment]
Then in that case, if I don't choose a cycle, the tasks won't be shown to me. I have to select a cycle to see which tasks are available

without any filters and cycle:
![image](https://user-images.githubusercontent.com/2676700/64123258-29bb9280-cda4-11e9-8bc0-25a6aaaa458b.png)

with cycle selected:
![image](https://user-images.githubusercontent.com/2676700/64123299-448e0700-cda4-11e9-8156-a711157d84be.png)

**Comment by Hasnayeen** [comment]
ok, its a bug then, I'll look into it.

**Comment by Hasnayeen** [comment]
Fixed by https://github.com/iluminar/goodwork/commit/b8b3941c51e2fb1f8b169e92e5580d26bb550785
