### ISSUE TITLE
add new member

### ISSUE THREAD

**Issue by ismaeljoseph** [iluminar/goodwork#640]
Hello I have install goodwork on my vps. Every look good. But i cannot add new member. 
Neither by mail ( can't send mail. Even though i have the same configuration on my voyager website which work fine). can't generate key. 

Is is possible to find some help?

**Comment by Hasnayeen** [comment]
have you added necessary env variable? all of the following variable are necessary in the `.env` 
```
MAIL_DRIVER=mailgun
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=2525
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM_NAME=
MAIL_FROM_ADDRESS=
```
if you're using `mailgun` then `MAILGUN_SECRET` & `MAILGUN_DOMAIN` are also needed, if you're using any other service then their respective secrets and key should be used.
If all of the above is setup correctly, then please check your log file in storage/log directory for error information and provide them. thanks

**Comment by ismaeljoseph** [comment]
[2019-10-06 01:36:40] local.ERROR: php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis:6379] {"exception":"[object] (Predis\\Connectio$
[stacktrace]
#0 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\\Connection\\AbstractConnection->onConnectionError('php_network_get...', 0)
#1 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\\Connection\\StreamConnection->createStreamSocket(Object(Predis\\Connection\\Paramete$
#2 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\\Connection\\StreamConnection->tcpStreamInitializer(Object(Predis\\Connection\\Parame$
#3 /var/www/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\\Connection\\StreamConnection->createResource()
#4 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\\Connection\\AbstractConnection->connect()
#5 /var/www/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\\Connection\\StreamConnection->connect()
#6 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(288): Predis\\Connection\\AbstractConnection->getResource()
#7 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\\Connection\\StreamConnection->write('*7\^M\
$4\^M\
EVAL\^M\
$...')
#8 /var/www/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\\Connection\\StreamConnection->writeRequest(Object(Predis\\Command\\ServerEval))
#9 /var/www/vendor/predis/predis/src/Client.php(331): Predis\\Connection\\AbstractConnection->executeCommand(Object(Predis\\Command\\ServerEval))
#10 /var/www/vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand(Object(Predis\\Command\\ServerEval))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(111): Predis\\Client->__call('eval', Array)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(211): Illuminate\\Redis\\Connections\\Connection->command('eval', Array)
#13 /var/www/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(208): Illuminate\\Redis\\Connections\\Connection->__call('eval', Array)
#14 /var/www/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(191): Illuminate\\Queue\\RedisQueue->migrateExpiredJobs('queues:default:...', 'queues:default$
#15 /var/www/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(167): Illuminate\\Queue\\RedisQueue->migrate('queues:default')
#16 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(264): Illuminate\\Queue\\RedisQueue->pop('default')
#17 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\\Queue\\Worker->getNextJob(Object(Illuminate\\Queue\\RedisQueue), 'default')
#18 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue$
#19 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#20 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#21 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#22 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\$
#24 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(591): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application)$
#25 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(192): Illuminate\\Container\\Container->call(Array)
#26 /var/www/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illum$
#27 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\I$
#28 /var/www/vendor/symfony/console/Application.php(915): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Comp$
#29 /var/www/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Objec$
#30 /var/www/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object$
#31 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Inp$
#32 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Inpu$
#33 /var/www/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Ou$

**Comment by ismaeljoseph** [comment]
[2019-10-06 01:36:40] local.ERROR: php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis:6379] {"exception":"[object] (Predis\\Connectio$
[stacktrace]
#0 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\\Connection\\AbstractConnection->onConnectionError('php_network_get...', 0)
#1 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\\Connection\\StreamConnection->createStreamSocket(Object(Predis\\Connection\\Paramete$
#2 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\\Connection\\StreamConnection->tcpStreamInitializer(Object(Predis\\Connection\\Parame$
#3 /var/www/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\\Connection\\StreamConnection->createResource()
#4 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\\Connection\\AbstractConnection->connect()
#5 /var/www/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\\Connection\\StreamConnection->connect()
#6 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(288): Predis\\Connection\\AbstractConnection->getResource()
#7 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\\Connection\\StreamConnection->write('*7\^M\
$4\^M\
EVAL\^M\
$...')
#8 /var/www/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\\Connection\\StreamConnection->writeRequest(Object(Predis\\Command\\ServerEval))
#9 /var/www/vendor/predis/predis/src/Client.php(331): Predis\\Connection\\AbstractConnection->executeCommand(Object(Predis\\Command\\ServerEval))
#10 /var/www/vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand(Object(Predis\\Command\\ServerEval))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(111): Predis\\Client->__call('eval', Array)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(211): Illuminate\\Redis\\Connections\\Connection->command('eval', Array)
#13 /var/www/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(208): Illuminate\\Redis\\Connections\\Connection->__call('eval', Array)
#14 /var/www/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(191): Illuminate\\Queue\\RedisQueue->migrateExpiredJobs('queues:default:...', 'queues:default$
#15 /var/www/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(167): Illuminate\\Queue\\RedisQueue->migrate('queues:default')
#16 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(264): Illuminate\\Queue\\RedisQueue->pop('default')
#17 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\\Queue\\Worker->getNextJob(Object(Illuminate\\Queue\\RedisQueue), 'default')
#18 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue$
#19 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#20 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#21 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#22 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\$
#24 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(591): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application)$
#25 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(192): Illuminate\\Container\\Container->call(Array)
#26 /var/www/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illum$
#27 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\I$
#28 /var/www/vendor/symfony/console/Application.php(915): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Comp$
#29 /var/www/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Objec$
#30 /var/www/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object$
#31 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Inp$
#32 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Inpu$
#33 /var/www/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Ou$

^G Get Help     ^O Write Out    ^W Where Is     ^K Cut Text     ^J Justify      ^C Cur Pos      M-U Undo        M-A Mark Text   M-] To Bracket  M-Q Previous
^X Exit         ^R Read File    ^\ Replace      ^U Uncut Text   ^T To Spell     ^_ Go To Line   M-E Redo

**Comment by ismaeljoseph** [comment]
When i use docker i have this log file:

[2019-10-06 03:00:07] local.ERROR: Connection could not be established with host smtp.googlemail.com [ #0] {"userId":1,"exception":"[object] (Swift_TransportException($
[stacktrace]
#0 /var/www/clients/client0/web8/web/goodwork/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishS$
#1 /var/www/clients/client0/web8/web/goodwork/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->$
#2 /var/www/clients/client0/web8/web/goodwork/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(484): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(259): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Mes$
#5 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(159): Illuminate\\Mail\\Mailer->send(Object(Illuminate\\Support$
#6 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\$
#7 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(160): Illuminate\\Mail\\Mailable->withLocale(NULL, Object(Closu$
#8 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(275): Illuminate\\Mail\\Mailable->send(Object(Illuminate\\Mail\\M$
#9 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(229): Illuminate\\Mail\\Mailer->sendMailable(Object(App\\Core\\Ma$
#10 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(127): Illuminate\\Mail\\Mailer->send(Object(App\\Core\\Mail$
#11 /var/www/clients/client0/web8/web/goodwork/app/Core/Http/Controllers/UserController.php(30): Illuminate\\Mail\\PendingMail->send(Object(App\\Core\\Mail\\SendInvita$
#12 [internal function]: App\\Core\\Http\\Controllers\\UserController->sentInvitationToRegister(Object(Illuminate\\Http\\Request))
#13 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#14 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callActio$
#15 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Obje$
#16 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#17 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#18 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{c$
#19 /var/www/clients/client0/web8/web/goodwork/app/Core/Http/Middleware/RedirectIfNotAdmin.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Obj$
#20 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Core\\Http\\Middleware\\RedirectIfNotAdmin->han$
#21 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->I$
#22 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings-$
#23 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate$
#24 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle(O$
#25 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Pipeline\\Pipeli$
#26 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrf$
#27 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->$
#28 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession$
#29 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline$
#30 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object$
#32 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate$
#33 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Ill$
#34 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Il$
#35 /var/www/clients/client0/web8/web/goodwork/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Fo$
#36 /var/www/clients/client0/web8/web/goodwork/app/Core/Http/Middleware/LocalizationMiddleware.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$

^G Get Help     ^O Write Out    ^W Where Is     ^K Cut Text     ^J Justify      ^C Cur Pos      M-U Undo        M-A Mark Text   M-] To Bracket  M-Q Previous
^X Exit         ^R Read File    ^\ Replace      ^U Uncut

**Comment by Hasnayeen** [comment]
how you installed the app? using single installer file or manually? run `docker ps` command to check all services are running. your redis service may be not running. pls check

**Comment by ismaeljoseph** [comment]
Can i give you full access to my vps for a fresh install ?

**Comment by Hasnayeen** [comment]
send me a mail
