### ISSUE TITLE
Add missing texts to english language localization file

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#652]
Lot of text from UI are missing in the English language localization file. Add all missing text to appropriate file inside `resources/lang/en` folder. `config/locale.php` contains map to route config info meaning which text goes to which file, e.g all text in `/` routes should be in `home` file. any text that doesn't belong to any route should go into `misc` file.

**Comment by ayrtonvwf** [comment]
Where are the original (untranslated) texts so that we can translate it to English?

**Comment by Hasnayeen** [comment]
@ayrtonvwf not translating rather adding English text that are being showed in the UI but not added to English localization file. the English language file is used to translate into other language.

**Comment by RageZBla** [comment]
@Hasnayeen I can work on this if you want? Just to be extra sure you just want to add entries like that `"foo" => "foo"`. Am I correct?

**Comment by Hasnayeen** [comment]
@RageZBla yes, that is correct

**Comment by RageZBla** [comment]
@Hasnayeen when you have the chance to review #660 :bowing_man:
