### ISSUE TITLE
Fix and improvements on Brazilian Portuguese translation

### ISSUE THREAD

**Issue by corodrigues** [iluminar/goodwork#654]
I found a little mistake in the file: <code>resources/lang/pt-BR/passwords.php</code>. The word <code>"confimação"</code> is misspeling... There is some improvements than can be made on the file <code>resources/lang/pt-BR/project.php</code> the first word for the translation of 'write your message...' is begining lowercase, I belive it will look a bit better with it start with a uppercase letter.

Can I make a PR with this fixes?

**Comment by Hasnayeen** [comment]
Sure, go ahead.
