### ISSUE TITLE
Add an api to delete direct message

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#657]
Add an api to delete a single direct message

**Comment by cdterry87** [comment]
I can try this one out.

**Comment by cdterry87** [comment]
I was looking at the application, and it looks like this feature already exists.  You can already delete a single message by clicking the three dots next to one of your messages and clicking "Delete".  Am I looking in the wrong spot?

**Comment by Hasnayeen** [comment]
that's group message not direct message, direct message is a private message to another user

**Comment by RageZBla** [comment]
I am giving a try as well.
