### ISSUE TITLE
Delete direct message (frontend, vue)

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#663]
Add a dropdown menu and delete option to delete a direct message. api is `direct-messages/direct_message_id`.
![goodwork](https://user-images.githubusercontent.com/9433499/66195857-57ed0480-e6b9-11e9-9a88-5dd7cc00a713.png)

**Comment by azisuazusa** [comment]
@Hasnayeen I will work on this issue

**Comment by Hasnayeen** [comment]
Sure, go ahead.
