### ISSUE TITLE
Add markdown format in editor (vue)

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#666]
Add markdown format support to editor in discussion board.

**Comment by theArtechnology** [comment]
I will work on that also

**Comment by bjgajjar** [comment]
@Hasnayeen - It seems like the markdown format is already there in Discussion board (Create post - Body) 

Do you want it for whole system?

**Comment by Hasnayeen** [comment]
@bjgajjar no, discussion post doesn't have markdown support, if you write in markdown format it doesn't convert it to html.

**Comment by bjgajjar** [comment]
@Hasnayeen - Try to send the PR by EOD :)
