### ISSUE TITLE
Add a load more button and load previous message on click (Vue)

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#693]
Add a load more button on top of message box in group message and load message when clicked.
api for message is `/messages` and already paginated

**Comment by ptrstovka** [comment]
Hi, can I pick this one?

**Comment by Hasnayeen** [comment]
Sure, go ahead.

**Comment by ptrstovka** [comment]
Unfortunately I wasn't able to find any spare time to do that. Leaving to someone else.
