### ISSUE TITLE
Fix avatar in notification dropdown (vue, tailwind)

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#697]
avatar gets squeezed in notification dropdown, it should be circle

**Comment by hallowcard13** [comment]
hi @Hasnayeen  can i handle this ?

**Comment by Hasnayeen** [comment]
Sure, go ahead.

**Comment by hallowcard13** [comment]
hi @Hasnayeen , do you know how can i simulate a notification so that i can view it ? or if you can share a sql file for that notfications table only that i can work with

**Comment by Hasnayeen** [comment]
@hallowcard13 just make `read_at` button in `notifications` table null

**Comment by mayanktiwaridotcom** [comment]
Hey if it just a style related issue may i point to one more which could probably be fixed along side.
1. Go to Project
2. Click on Add Member
the dialog opens but its position with z-index is probably not right, buttons are hiding behind the Menu bar.
have to do ctrl+----- many times to get save or cancel button
![image](https://user-images.githubusercontent.com/11807296/70117336-c8070f00-1697-11ea-8cc9-d93012887da7.png)

**Comment by mayanktiwaridotcom** [comment]
@Hasnayeen Shall I open a separate bug for above commented issue ? 
Is it possible that you or someone can introduce me to the project structure component collaboration so I can also contribute to solve some bugs ?

**Comment by Hasnayeen** [comment]
yes, a separate issue will be better.
wiki has information about contribution guideline, https://github.com/iluminar/goodwork/wiki/Contribution-Guideline
also you can join discord server if you need more info you can ask there also https://discord.gg/4DvTQsc

**Comment by mayanktiwaridotcom** [comment]
@Hasnayeen Done with local setup, forked the repo and ready to help, creating new issue for above.
