### ISSUE TITLE
Add github action to run php-cs-fixer to autofix code style issues

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#725]
This action should run on any pull request created against dev branch to check js lint and auto fix them. Should use [this](https://gist.github.com/Hasnayeen/5a4950dfce0c24331556350bb5b676bd) ruleset for fixing

**Comment by RageZBla** [comment]
@Hasnayeen I can take a look but is OK to apply the fixer to the whole codebase?

**Comment by Hasnayeen** [comment]
yes
