### ISSUE TITLE
Add edit option on message board (VueJS)

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork#729]
Add edit option for message in message board. api to use is `message/{message_id}`

**Comment by thesanjeevsharma** [comment]
Hello, I am taking this issue!

**Comment by Hasnayeen** [comment]
@thesanjeevsharma  Sure, go ahead. But if you decide not to do this later on please mention on the issue so that other can pick it up.

**Comment by thesanjeevsharma** [comment]
@Hasnayeen discontinuing this; facing issues Laravel setup!

**Comment by ewatch** [comment]
I‘d like to look into this topic today.

**Comment by Hasnayeen** [comment]
Sure, go ahead. But if you decide not to do this later on please mention on the issue so that other can pick it up.

**Comment by ewatch** [comment]
First draft of my implementation.
I still have to get rid of one issue where the list of messages are not yet updated properly after editing even if the array of messages are changed in the way Vue expects it to be changed (meaning through their proxy methods) and not directly overwriting and element through accessing the Array through an index.

**Comment by ewatch** [comment]
I fixed the rendering problem now and changed the v-for key ot message.body as the the id doesn't change when updating the message but the body does. This is also recommended in the VueJS documentation.

Thanks and best regards,
Jan

**Comment by Hasnayeen** [comment]
@ewatch thanks for the pr, nice work :+1:
