### ISSUE TITLE
manual install config

### ISSUE THREAD

**Issue by econwang** [iluminar/goodwork#734]
I strictly follow the guide in <https://github.com/iluminar/goodwork/wiki/Installation#setup-usual-way-if-youre-not-using-docker>, and resulting a webpage just show `OK`, how to connect to the app? not sure whether I miss any config.

**Comment by Hasnayeen** [comment]
how are you running the app?

**Comment by msslava** [comment]
@econwang There are a lot of nuances that are not described in this guide.
I got a working project based on this guide, but I need to understand from where everything went wrong?
If you have a clean system (for example Ubuntu 18 server):
1) install nginx
2) install php-fmp
configure it
3) install mysql-server
create database, user 
4) install redis-server
5) install laravel-echo-server
After that, you must add true settings in .env.
Check nginx config (for example docker/site.conf) and after that app must work.

It seems that's all

**Comment by mayanktiwaridotcom** [comment]
@econwang It was easy, Assuming you have already downloaded/cloned the files you can follow these steps exactly in order, i was able to set up on my localhost.

1. I just created a localdomain in apache configuration "goodlwork.local" pointing to goodwork/public directory and added it in the etc/hosts file so dns lookup would work.

2. Once all the files in goodwork root directory run "composer install".

3. install redis server and run it, i was able to do simply by sudo apt-get install redis-server.
3.1. test redis server by redis-cli and then ping.

4. edit .env file to point to right configurations for domain, database, redis and email etc.

5. php artisan key:generate

6. php artisan storage:link

7. php artisan migrate --seed

8. php artisan passport:install (i faced the problem with database at this point, if I run this command before migrate command so once database is populated then this command works fine).

9. npm install

10. npm install -g laravel-echo-server
10.1. configure the laravel-echo-server.json file with required parameters(if on production it may required ssl configurations and certificate files).
10.2. laravel-echo-server start(run it in background).

11. php artisan queue:work redis --sleep=1 --tries=1 (run it in background).

**Comment by econwang** [comment]
many thanks,  it works
