### ISSUE TITLE
Files not loading

### ISSUE THREAD

**Issue by msslava** [iluminar/goodwork#747]
### Description:
![error4](https://user-images.githubusercontent.com/3504940/67552059-e978f080-f712-11e9-90d3-2ad014c77486.jpg)
![error3](https://user-images.githubusercontent.com/3504940/67552060-e978f080-f712-11e9-9c7a-86b41f1ea56f.jpg)

**Comment by Hasnayeen** [comment]
fixed by edf5c5c, check if the issue is solved

**Comment by msslava** [comment]
It is doesn't work. I get new error
![error](https://user-images.githubusercontent.com/3504940/67618354-fd961e00-f7f6-11e9-9574-b7dbcb9f3ea7.png)

**Comment by msslava** [comment]
If I upload files through the Files menu - also an error

**Comment by Hasnayeen** [comment]
are you trying this in local or in the demo site?

**Comment by msslava** [comment]
on my demo site

**Comment by Hasnayeen** [comment]
so not on the https://goodworkfor.life/ site? can you describe how to reproduce this? I can't reproduce this on my local or the demo site

**Comment by msslava** [comment]
no, on my demo site. You can use my demosite and login as guest, if you want.
http://91.77.162.158/

**Comment by Hasnayeen** [comment]
do you have the latest code?

**Comment by Hasnayeen** [comment]
can you try clearing route cache to see if its solves the problem

**Comment by Hasnayeen** [comment]
also you've to run new migration for file uploading to work in file tab

**Comment by msslava** [comment]
Now it's work, thanks

**Comment by msslava** [comment]
**But** 
If you reopen the post for editing, then the files are not loaded
