### ISSUE TITLE
Missing step in "Manual installation" wiki

### ISSUE THREAD

**Issue by sierrafayad** [iluminar/goodwork#749]
There is a missing step here,
[Manual Installation](https://github.com/iluminar/goodwork/wiki/Installation#setup-usual-way-if-youre-not-using-docker)
### 3 Setup application
> $ git checkout master # use dev branch for local development
> $ git pull origin master # use dev branch for local development
> $ composer install
> $ cp .env.example .env
> $ php artisan key:generate
> $ php artisan storage:link
> `$ php artisan passport:install`
> $ php artisan migrate --seed
> $ npm install

**Comment by Hasnayeen** [comment]
updated, thanks for informing
