### ISSUE TITLE
View All Notification fetch JSON response instead of View

### ISSUE THREAD

**Issue by mayanktiwaridotcom** [iluminar/goodwork#796]
### Your environment:
OS: Linux
Browser: Firefox

### Description:
When we click on notification icon and "View All" it gives json response instead of View.

### Steps To Reproduce:
Click on bell icon on top right corner along the message icon.
click on View All link at the bottom of it.

**Comment by Lessad** [comment]
Having the same here, only a JSON response saying "success"

**Comment by Hasnayeen** [comment]
fixed by 57f1a53
