### ISSUE TITLE
Popup partials for member lists and add member hide behind menu tabs.

### ISSUE THREAD

**Issue by mayanktiwaridotcom** [iluminar/goodwork#805]
### Your environment:
Linux
Any Browser

### Description:
While adding a member or viewing member list in the projects add and cancel button hide behind the navigation bar.
![image](https://user-images.githubusercontent.com/11807296/70413129-36c5dd00-1a89-11ea-8554-7329b5bdc024.png)

### Steps To Reproduce:
1. Go to projects, 
2. click on add member or view member list

**Comment by atilacamurca** [comment]
Same on other modals like Add member:

![image](https://user-images.githubusercontent.com/508624/72814020-2043a180-3c43-11ea-8cd6-d9c7c99864f1.png)

**Comment by Hasnayeen** [comment]
Fixed
