### ISSUE TITLE
`Echo Is Not Defined`: socket not working, Echo not connecting

### ISSUE THREAD

**Issue by dougblackjr** [iluminar/goodwork#876]
### Your environment:
Ubuntu 19.04

### Description:
`socket.io` is not loading, console error reported of `Echo is not defined`

### Steps To Reproduce:
- Clone repo.
- Follow all instructions as listed here: [https://github.com/iluminar/goodwork/wiki/Installation#setup-usual-way-if-youre-not-using-docker](https://github.com/iluminar/goodwork/wiki/Installation#setup-usual-way-if-youre-not-using-docker)
- Login

**Comment by Hasnayeen** [comment]
@dougblackjr which `laravel-echo-server.json` file are you using to run echo-server? If you're running dev version then start echo server with `laravel-echo-server.dev.json` file, like below
`laravel-echo-server start --dir=laravel-echo-server.dev.json`

**Comment by dougblackjr** [comment]
@Hasnayeen Using the production one. Here is my current config (with some variables changed):
```
{
  "authHost": "https://url-of-site",
  "authEndpoint": "/broadcasting/auth",
  "clients": [
    {
      "appId": "bec9d450fbf2af78",
      "key": "adeb2fe782d9d3dcd955ac5a88aff184"
    }
  ],
  "database": "redis",
  "databaseConfig": {
    "redis": {},
    "sqlite": {
      "databasePath": "/database/laravel-echo-server.sqlite"
    }
  },
  "devMode": false,
  "host": null,
  "port": "6001",
  "protocol": "https",
  "socketio": {},
  "secureOptions": 67108864,
  "sslCertPath": "/etc/nginx/ssl/------.crt",
  "sslKeyPath": "/etc/nginx/ssl/------.key",
  "sslCertChainPath": "",
  "sslPassphrase": "",
  "subscribers": {
    "http": true,
    "redis": true
  },
  "apiOriginAllow": {
    "allowCors": false,
    "allowOrigin": "",
    "allowMethods": "",
    "allowHeaders": ""
  }
}
```

My only question is whether the app ID and key need to be changed, those both came over what was in the repo.

**Comment by Hasnayeen** [comment]
ID and key doesn't need to be changed, after starting echo server do you see any error? what's the last few output lines?

**Comment by dougblackjr** [comment]
No error, just says that server is started.
```
L A R A V E L  E C H O  S E R V E R

version 1.6.0

Starting server...

✔  Running at localhost on port 6001
✔  Listening for http events...
✔  Listening for redis events...

Server ready!
```

**Comment by Hasnayeen** [comment]
any error on console? also check the network tab for socket.js call, whats the response of that?

**Comment by dougblackjr** [comment]
socket.js call times out without any response.
![Screen Shot 2020-02-21 at 8 16 18 AM](https://user-images.githubusercontent.com/6020323/75037599-8f9af400-5482-11ea-968d-26eab54af407.png)

Error in console is `Echo is not defined.`
![Screen Shot 2020-02-21 at 8 16 32 AM](https://user-images.githubusercontent.com/6020323/75037598-8f9af400-5482-11ea-9fbb-c6d277a9ca0d.png)

**Comment by Hasnayeen** [comment]
check the url for socket.js call?

**Comment by dougblackjr** [comment]
Correct, that file is not in the repo. Did I miss a step in the installation process?

**Comment by Hasnayeen** [comment]
maybe reinstall `laravel-echo-server` , `socket.io` is a dependency of `laravel-echo-server` and will be available from echo server not from repo public directory

**Comment by dougblackjr** [comment]
I just went ahead and moved to pusher for now. Thank you!

**Comment by Hasnayeen** [comment]
sorry could not help you further, but hopefully you figured it out
