### ISSUE TITLE
You do not have permission for this action

### ISSUE THREAD

**Issue by Lessad** [iluminar/goodwork#906]
Hi,

I managed to install Goodwork and it works well so far, but none of the roles has rights to do anything I get the message "You do not have permission for this action" when i try to create a team, or change the permissions.

I am logged in as admin, but all the boxes are unchecked.. anyone who had this issue ?

Thank you

**Comment by Hasnayeen** [comment]
what method you used to install the app? 
In the admin page check the "Roles & permission" section, you can edit permission from there also

**Comment by Hasnayeen** [comment]
@Lessad a fix has been pushed, check if this solves the error
run `./cmd art migrate:fresh --seed`

**Comment by Lessad** [comment]
On it

**Comment by Lessad** [comment]
Issue fixed, I am now able to acces the Admin Panel, create teams and edit permissions :)
