### ISSUE TITLE
Member link invitation ends up as Guest

### ISSUE THREAD

**Issue by Lessad** [iluminar/goodwork#915]
### Your environment:
Ubuntu server 18.04

### Description:
Created a link for "Member" role, but ended up with Guests

### Steps To Reproduce:
Log in as Admin
Go to Admin Panel
Parameters Panel then Invitations
Generate a link for Member
Use the link to create a user
Go back in Admin Panel

**Comment by Lessad** [comment]
Fixed it, apparently having an office named Headquarter is compulsory to have it work. I deleted mine because I did not need it, but in the end if you do delete it all Registration will give a "Guest" because the script cannot finish it's work.

Hope it helps !

**Comment by Hasnayeen** [comment]
Will look into this and make necessary change to be able to delete "Headquarter" not affecting the invite.

**Comment by Hasnayeen** [comment]
this has been fixed now (by 19e080c) , can you confirm please?
