### ISSUE TITLE
[Feature Request] Default task Filter: All instead of To Do

### ISSUE THREAD

**Issue by Lessad** [iluminar/goodwork#937]
Hi,

Just an idea for a (maybe) better viewing experience of tasks. When you enter a project you see all the To Do's which is great for knowing what is next but to grasp the progression of a progress wouldn't it be better to see all tasks by default ?

That way you can assess how much work was done, or avoid forgetting about any cancelled task for instance. 

Maybe a good mix of the two would be to display all tasks but To Do's first in the list

What do you think ? :)

**Comment by Hasnayeen** [comment]
yeah all list grouped by status can be a good idea. Will look into it. Thanks

**Comment by Hasnayeen** [comment]
Feature added
