### ISSUE TITLE
Wiki Documentation Note: Should use HTTPS for Clone URL

### ISSUE THREAD

**Issue by zicklag** [iluminar/goodwork#941]
I was just browsing the [install instructions](https://github.com/iluminar/goodwork/wiki/Installation#setup-using-single-file-installer) when I pasted the git clone URL into a brand new server and it failed because it was an ssh clone URL instead of an HTTPS clone URL. It would be more universal to use HTTPS for the clone URL in the installation instructions.

I would have fixed it myself, but it doesn't look like I can edit the wiki.

**Comment by Hasnayeen** [comment]
done, thanks for noticing.
