### ISSUE TITLE
Different database

### ISSUE THREAD

**Issue by it-werxdotca** [iluminar/goodwork#945]
Can there be more databases to be used? Like MariaDB, Mysql...

**Comment by Hasnayeen** [comment]
not sure what you mean. the app currently use mysql

**Comment by nmindz** [comment]
@it-werxdotca MySQL and MariaDB are mostly interchangeable. Also, Laravel/EloquentORM should work seamlessly with whatever DB you opt for, except if the application makes usage of distribution-specific SQL features.

AFAIK Goodwork only officially supports MySQL, but you may change the SQL driver from the `.env` file at your own risk and test for yourself. Your mileage may vary, though.

**Comment by SamJakob** [comment]
I'm using it with PostgreSQL in production successfully.

**Comment by nmindz** [comment]
@Hasnayeen I guess this issue may be closed.
