### ISSUE TITLE
Tags Dropdown empty

### ISSUE THREAD

**Issue by Lessad** [iluminar/goodwork#950]
### Your environment:
Ubuntu 18.04 server
Lastest Goodwork installed

### Description:
Tags not showing up in filters

### Steps To Reproduce:
Add/Enter a project
Create a task
Create a tag
Add tag to project then task
Click on Filter
No tags in the dropdown

I hope it will be enough to reproduce it, thank you !

**Comment by Rafatlne** [comment]
@Lessad I have committed fixed of this bug. Hope it will get merged soon.

**Comment by Lessad** [comment]
That was quick ! Thank you for sharing
