### ISSUE TITLE
Error when saving with empty description

### ISSUE THREAD

**Issue by Lessad** [iluminar/goodwork#957]
### Your environment:
Ubuntu Server 18.04
Latest build of Goodwork

### Description:
The user is able to create a task without description but cannot edit it (for example to change the Due Date) without adding a description. Error "The given data is invalid"

### Steps To Reproduce:
Create a task without description
Select the task and hit Edit
Change the Due Date
Click on Confirm

**Comment by arifpavel** [comment]
@Hasnayeen  I want to fix this. Can I?

**Comment by Hasnayeen** [comment]
Sure, go ahead. But if you decide not to do this later on please mention on the issue so that other can pick it up.
