### ISSUE TITLE
Can't run behind Reverse Proxy

### ISSUE THREAD

**Issue by tiredofit** [iluminar/goodwork#997]
### Your environment:

Docker (own image) w/Nginx
Traefik Reverse Proxy

### Description:

I cannot connect to Goodwork behind a SSL Terminating reverse proxy. When attempting to visit the site URLs are returned as http instead of https. Also have `fastcgi_param  HTTPS 'on';` in nginx configuration in attempt to trick the application.

### Steps To Reproduce:

Set env
`APP_URL=https://hostname.example.com`
`APP_PORT=80`

Utilize reverse proxy and see results.

-- If I can get this working I will publicly release the Docker Image that does automatic configuration of config and a few other tricks.

**Comment by Hasnayeen** [comment]
@tiredofit set `APP_PROTOCOL` value in `.env` file to `https`

**Comment by tiredofit** [comment]
Fantastic - This made everything work.
